"""Explicit repo-intelligence workflow opt-in validation.

This module is deliberately read-only. It validates an operator-provided
Markdown handoff before a workflow may treat it as visible input, but it does
not inject context, write artifacts, expose MCP tools, or call adapters.
"""

from __future__ import annotations

import hashlib
import re
from pathlib import Path
from typing import Any, Mapping

JsonDict = dict[str, Any]

SUPPORT_TIER = "beta_explicit_handoff"
SOURCE = "explicit_handoff_file"
CURRENT_ONLY = "current_only"
COMMAND_CONTRACT = "python3 -m ao_kernel repo query --output markdown"
_HEX64_RE = re.compile(r"^[a-f0-9]{64}$")
_NAMESPACE_RE = re.compile(r"^repo_chunk::[^:]+::[^:]+::$")
_CHUNK_HEADING_RE = re.compile(r"^### \d+\. `(?P<path>.+):(?P<start>\d+)-(?P<end>\d+)`$")


def validate_repo_intelligence_workflow_opt_in(
    config: Mapping[str, Any] | None,
    *,
    project_root: Path,
) -> JsonDict:
    """Validate explicit repo-intelligence workflow context opt-in.

    Disabled or absent config is a no-op. Enabled config must point at a
    Markdown file generated by ``repo query --output markdown`` and must keep
    the beta explicit-handoff boundary intact.
    """
    if not config or config.get("enabled") is not True:
        return {
            "status": "disabled",
            "enabled": False,
            "decision": "repo_intelligence_context_not_enabled",
        }

    root = project_root.resolve()
    findings: list[str] = []
    source = _string(config.get("source"))
    support_tier = _string(config.get("support_tier"))
    require_fresh = config.get("require_fresh")
    expected_namespace = _string(config.get("expected_namespace"))
    handoff_path_value = _string(config.get("handoff_path"))
    expected_sha256 = _string(config.get("expected_markdown_sha256"))

    if source != SOURCE:
        findings.append("source_not_explicit_handoff_file")
    if support_tier != SUPPORT_TIER:
        findings.append("support_tier_not_beta_explicit_handoff")
    if require_fresh is not True:
        findings.append("require_fresh_not_true")
    if not _NAMESPACE_RE.fullmatch(expected_namespace):
        findings.append("expected_namespace_invalid")
    if not handoff_path_value:
        findings.append("handoff_path_missing")

    handoff_path = _resolve_handoff_path(handoff_path_value, root)
    if handoff_path is None:
        findings.append("handoff_path_escape")
    elif not handoff_path.is_file():
        findings.append("handoff_file_missing")

    markdown = ""
    markdown_sha256 = ""
    if handoff_path is not None and handoff_path.is_file():
        markdown = handoff_path.read_text(encoding="utf-8")
        markdown_sha256 = hashlib.sha256(markdown.encode("utf-8")).hexdigest()
        if expected_sha256 and expected_sha256 != markdown_sha256:
            findings.append("handoff_sha256_mismatch")

    if markdown:
        findings.extend(_validate_markdown(markdown, expected_namespace=expected_namespace))

    if findings:
        return {
            "status": "blocked",
            "enabled": True,
            "decision": "blocked_repo_intelligence_workflow_opt_in",
            "findings": sorted(set(findings)),
            "handoff": {
                "path": str(handoff_path) if handoff_path is not None else handoff_path_value,
                "markdown_sha256": markdown_sha256,
            },
            "support_widening": False,
            "production_platform_claim": False,
        }

    metadata = _extract_metadata(markdown)
    return {
        "status": "accepted",
        "enabled": True,
        "decision": "accepted_repo_intelligence_workflow_opt_in",
        "handoff": {
            "path": str(handoff_path),
            "markdown_sha256": markdown_sha256,
            "mode": "explicit_operator_markdown",
            "support_tier": SUPPORT_TIER,
        },
        "source_metadata": metadata,
        "safety": {
            "hidden_injection": False,
            "root_export": False,
            "mcp_exposure": False,
            "context_compiler_auto_feed": False,
            "vector_writes": False,
            "artifact_writes": False,
        },
        "support_widening": False,
        "production_platform_claim": False,
    }


def _validate_markdown(markdown: str, *, expected_namespace: str) -> list[str]:
    findings: list[str] = []
    if "# Repo Query Context Pack" not in markdown:
        findings.append("handoff_title_missing")
    if "## Handoff Contract" not in markdown:
        findings.append("handoff_contract_missing")
    if "## Handoff Provenance" not in markdown:
        findings.append("handoff_provenance_missing")
    if "## Source Artifacts" not in markdown:
        findings.append("source_artifacts_missing")

    project_index = _section_table(markdown, "Project And Index")
    provenance = _section_table(markdown, "Handoff Provenance")
    source_artifacts = _section_table(markdown, "Source Artifacts")

    if project_index.get("Vector key prefix") != expected_namespace:
        findings.append("namespace_mismatch")
    if provenance.get("Command contract") != COMMAND_CONTRACT:
        findings.append("command_contract_missing")
    if provenance.get("Output mode") != "stdout-only Markdown":
        findings.append("output_mode_not_stdout_markdown")
    if provenance.get("Read/write mode") != "read-only retrieval; no artifact, vector, root, MCP, or memory writes":
        findings.append("read_write_mode_not_read_only")
    if provenance.get("Support tier") != SUPPORT_TIER:
        findings.append("handoff_support_tier_invalid")
    if provenance.get("Freshness state") != CURRENT_ONLY:
        findings.append("freshness_not_current_only")
    if provenance.get("Hidden injection") != "disabled; operator must provide this Markdown as visible input":
        findings.append("hidden_injection_not_disabled")
    if provenance.get("Root export") != "disabled":
        findings.append("root_export_not_disabled")
    if provenance.get("MCP exposure") != "disabled":
        findings.append("mcp_exposure_not_disabled")
    if provenance.get("context_compiler auto-feed") != "disabled":
        findings.append("context_compiler_auto_feed_not_disabled")

    if source_artifacts.get("freshness_state") != CURRENT_ONLY:
        findings.append("source_artifact_freshness_not_current_only")
    if source_artifacts.get("stale_candidates") != "0":
        findings.append("stale_candidates_not_zero")
    for key in ("repo_chunks_sha256", "repo_vector_index_manifest_sha256"):
        if not _HEX64_RE.fullmatch(source_artifacts.get(key, "")):
            findings.append(f"{key}_invalid")

    chunk_metadata = _chunk_metadata(markdown)
    if not chunk_metadata:
        findings.append("retrieved_chunks_missing")
    for chunk in chunk_metadata:
        source_path = chunk["source_path"]
        if Path(source_path).is_absolute() or ".." in Path(source_path).parts:
            findings.append("source_path_escape")
        if chunk["start_line"] > chunk["end_line"]:
            findings.append("invalid_line_range")
        if chunk["metadata"].get("Content status") != "current":
            findings.append("chunk_content_status_not_current")
        if not _HEX64_RE.fullmatch(chunk["metadata"].get("Content SHA256", "")):
            findings.append("chunk_content_sha256_invalid")

    return findings


def _extract_metadata(markdown: str) -> JsonDict:
    project_index = _section_table(markdown, "Project And Index")
    source_artifacts = _section_table(markdown, "Source Artifacts")
    chunks = _chunk_metadata(markdown)
    return {
        "vector_namespace_key_prefix": project_index.get("Vector key prefix", ""),
        "repo_chunks_sha256": source_artifacts.get("repo_chunks_sha256", ""),
        "repo_vector_index_manifest_sha256": source_artifacts.get("repo_vector_index_manifest_sha256", ""),
        "freshness_state": source_artifacts.get("freshness_state", ""),
        "stale_candidates": int(source_artifacts.get("stale_candidates", "0")),
        "retrieved_chunks": len(chunks),
        "source_paths": [chunk["source_path"] for chunk in chunks],
        "content_sha256": [chunk["metadata"].get("Content SHA256", "") for chunk in chunks],
    }


def _resolve_handoff_path(value: str, root: Path) -> Path | None:
    if not value:
        return None
    raw = Path(value)
    candidate = raw if raw.is_absolute() else root / raw
    resolved = candidate.resolve()
    if not _is_relative_to(resolved, root):
        return None
    return resolved


def _section_table(markdown: str, section: str) -> dict[str, str]:
    lines = markdown.splitlines()
    header = f"## {section}"
    try:
        start = lines.index(header) + 1
    except ValueError:
        return {}
    rows: dict[str, str] = {}
    for line in lines[start:]:
        if line.startswith("## "):
            break
        if not line.startswith("|"):
            continue
        cells = [cell.strip().replace("\\|", "|") for cell in line.strip().strip("|").split("|")]
        if len(cells) < 2 or cells[0] in {"---", "Field", "Artifact"}:
            continue
        if set(cells[0]) == {"-"}:
            continue
        rows[cells[0]] = cells[1]
    return rows


def _chunk_metadata(markdown: str) -> list[JsonDict]:
    lines = markdown.splitlines()
    chunks: list[JsonDict] = []
    for index, line in enumerate(lines):
        match = _CHUNK_HEADING_RE.match(line)
        if match is None:
            continue
        metadata: dict[str, str] = {}
        for table_line in lines[index + 1 :]:
            if table_line.startswith("### ") or table_line.startswith("## "):
                break
            if not table_line.startswith("|"):
                continue
            cells = [cell.strip().replace("\\|", "|") for cell in table_line.strip().strip("|").split("|")]
            if len(cells) < 2 or cells[0] in {"---", "Field"}:
                continue
            if set(cells[0]) == {"-"}:
                continue
            metadata[cells[0]] = cells[1]
        chunks.append(
            {
                "source_path": match.group("path"),
                "start_line": int(match.group("start")),
                "end_line": int(match.group("end")),
                "metadata": metadata,
            }
        )
    return chunks


def _string(value: Any) -> str:
    return value if isinstance(value, str) else ""


def _is_relative_to(path: Path, root: Path) -> bool:
    try:
        path.relative_to(root)
    except ValueError:
        return False
    return True

